### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by WalrusInAnus** [eric-bixby/auto-sort-bookmarks-pm#1]
Can you update the addon please? It's been untouched since 2017.

**Comment by eric-bixby** [comment]
@WalrusInAnus -- There's an expression, "if it ain't broke, don't fix it."  If there are problems, I haven't been hearing about them.

**Comment by WalrusInAnus** [comment]
Well, ok, but there is a reason why the original addon has been updated numerous times since then I guess?

**Comment by eric-bixby** [comment]
Most of the updates to the web-ext version have been Firefox-specific.  Feature-wise, I think PM is just missing support for other languages.
Anyway, if I have time, I would like to convert this version into the web-ext version and separate the browser-specific stuff into classes with a standard interface.  A single repo would be easier to maintain.
But right now, that's on my wishlist.  I need the time/energy to do it.

**Comment by eric-bixby** [comment]
I almost forgot.  I thought this version was no longer needed.  Didn't Palemoon update to support web-extensions?

If so, you can use this version: https://github.com/eric-bixby/auto-sort-bookmarks-webext
Which is available on the Mozilla Add-on site: https://addons.mozilla.org/en-US/firefox/addon/auto-sort-bookmarks/

**Comment by WalrusInAnus** [comment]
Honestly I have no idea. I am just a lowlife user with no knowledge of web development :D
But I don't think so, otherwise people wouldn't be moaning about more and more websites not workin in PM correctly or at all :D

**Comment by eric-bixby** [comment]
I remember now, thanks to Wikipedia: https://en.wikipedia.org/wiki/Pale_Moon
Basilisk, a sibling of Pale Moon, had support for web extensions, but later dropped support and has been discontinued.
Anyway, I'll rename the title of this issue to remind me about adding PM support to the webext repo (which means renaming that repo because it would then support multiple browsers from one repo).

**Comment by eric-bixby** [comment]
Scratch that idea.  I remember why these are separate repos.  The webext version uses web-extension-helper (weh) to manage user preferences (doesn't support Pale Moon).  There just is no value in combining them into a single repo.

Anyway, long story short, if there's a feature you'd like or bug in the Pale Moon version, then create a new item for it here.
